server:
    port: 8001
spring:
    application:
        name: cloud-config-server
    profiles:
        active: git
    cloud:
        config:
            server:
                git:
                    uri:  https://github.com/duzie/2os
                    search-paths: cloud-config-server
eureka:
    client:
        service-url:
            defaultZone: http://2os.win:8000/eureka
